=== the-fab-cube/flesh-and-blood-cards/json-schema/card-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "An array of all of the existing cards in Flesh and Blood, with each item being a unique card.",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "unique_id": {
                "description": "A UUID representing the card within this data set.",
                "type": "string"
            },
            "name": {
                "description": "The name of the card.",
                "type": "string"
            },
            "pitch": {
                "description": "The pitch value of the card. Can be a number or blank.",
                "type": "string"
            },
            "cost": {
                "description": "The cost of the card. Can be a number, X, XX, X and a number, or blank.",
                "type": "string"
            },
            "power": {
                "description": "The power of the card. Can be a number, *, X, or blank.",
                "type": "string"
            },
            "defense": {
                "description": "The defense of the card. Can be a number, *, or blank.",
                "type": "string"
            },
            "health": {
                "description": "The health of the card. Can be a number or blank.",
                "type": "string"
            },
            "intelligence": {
                "description": "The intelligence of the card. Can be a number or blank.",
                "type": "string"
            },
            "types": {
                "description": "The types of the card (includes all types, subtypes, etc).",
                "type": "array",
                "items": {
                    "description": "An individual type.",
                    "type": "string"
                }
            },
            "card_keywords": {
                "description": "The keywords inherent to the card. Includes conditional keywords, but does not include keywords that are part of the card's activated and triggered abilities.",
                "type": "array",
                "items": {
                    "description": "An individual keyword.",
                    "type": "string"
                }
            },
            "abilities_and_effects": {
                "description": "The activated abilities and once per turn effects of the cards. Just contains what type of ability it is, not the ability itself. (Ex: Once per Turn Action)",
                "type": "array",
                "items": {
                    "description": "An individual ability.",
                    "type": "string"
                }
            },
            "ability_and_effect_keywords": {
                "description": "The keywords that are part of the card's activated and triggered abilities.",
                "type": "array",
                "items": {
                    "description": "An individual keyword.",
                    "type": "string"
                }
            },
            "granted_keywords": {
                "description": "The keywords that the card grants to other objects.",
                "type": "array",
                "items": {
                    "description": "An individual keyword.",
                    "type": "string"
                }
            },
            "removed_keywords": {
                "description": "The keywords that the card removes from other objects.",
                "type": "array",
                "items": {
                    "description": "An individual keyword.",
                    "type": "string"
                }
            },
            "interacts_with_keywords": {
                "description": "The keywords that the card interacts with outside of granting/removing.",
                "type": "array",
                "items": {
                    "description": "An individual keyword.",
                    "type": "string"
                }
            },
            "functional_text": {
                "description": "The functional text of the card, formatted in Markdown.",
                "type": "string"
            },
            "functional_text_plain": {
                "description": "The functional text of the card, formatted in plain text.",
                "type": "string"
            },
            "type_text": {
                "description": "The full type text box of the card.",
                "type": "string"
            },
            "played_horizontally": {
                "description": "A boolean representing if the card is played and displayed horizontally.",
                "type": "boolean"
            },
            "blitz_legal": {
                "description": "A boolean representing if the card is legal in Blitz (not including bans or suspensions).",
                "type": "boolean"
            },
            "cc_legal": {
                "description": "A boolean representing if the card is legal in Classic Constructed (not including bans or suspensions).",
                "type": "boolean"
            },
            "commoner_legal": {
                "description": "A boolean representing if the card is legal in Commoner (not including bans or suspensions).",
                "type": "boolean"
            },
            "blitz_living_legend": {
                "description": "A boolean representing if the card is Living Legend in Blitz.",
                "type": ["boolean"]
            },
            "blitz_living_legend_start": {
                "description": "The date the card became Living Legend in Blitz (will not be present otherwise).",
                "type": ["string"]
            },
            "cc_living_legend": {
                "description": "A boolean representing if the card is Living Legend in Classic Constructed.",
                "type": ["boolean"]
            },
            "cc_living_legend_start": {
                "description": "The date the card became Living Legend in Classic Constructed (will not be present otherwise).",
                "type": ["string"]
            },
            "blitz_banned": {
                "description": "A boolean representing if the card is currently banned in Blitz.",
                "type": ["boolean"]
            },
            "blitz_banned_start": {
                "description": "The date the card became banned in Blitz (will not be present otherwise).",
                "type": ["string"]
            },
            "cc_banned": {
                "description": "A boolean representing if the card is currently banned in Classic Constructed.",
                "type": ["boolean"]
            },
            "cc_banned_start": {
                "description": "The date the card became banned in Classic Constructed (will not be present otherwise).",
                "type": ["string"]
            },
            "commoner_banned": {
                "description": "A boolean representing if the card is currently banned in Commoner.",
                "type": ["boolean"]
            },
            "commoner_banned_start": {
                "description": "The date the card became banned in Commoner (will not be present otherwise).",
                "type": ["string"]
            },
            "upf_banned": {
                "description": "A boolean representing if the card is currently banned in Ultimate Pit Fight.",
                "type": ["boolean"]
            },
            "upf_banned_start": {
                "description": "The date the card became banned in Ultimate Pit Fight (will not be present otherwise).",
                "type": ["string"]
            },
            "blitz_suspended": {
                "description": "A boolean representing if the card is currently banned in Blitz.",
                "type": ["boolean"]
            },
            "blitz_suspended_start": {
                "description": "The date the card became suspended in Blitz (will not be present otherwise).",
                "type": ["string"]
            },
            "blitz_suspended_end": {
                "description": "Represents when the card is set to be unsuspended in Blitz. Contains a displayable text describing when it will be unsuspended if it is currently suspended (will not be present otherwise).",
                "type": ["string"]
            },
            "cc_suspended": {
                "description": "A boolean representing if the card is currently banned in Classic Constructed.",
                "type": ["boolean"]
            },
            "cc_suspended_start": {
                "description": "The date the card became suspended in Classic Constructed (will not be present otherwise).",
                "type": ["string"]
            },
            "cc_suspended_end": {
                "description": "Represents when the card is set to be unsuspended in Classic Constructed. Contains a displayable text describing when it will be unsuspended if it is currently suspended (will not be present otherwise).",
                "type": ["string"]
            },
            "commoner_suspended": {
                "description": "A boolean representing if the card is currently banned in Commoner.",
                "type": ["boolean"]
            },
            "commoner_suspended_start": {
                "description": "The date the card became suspended in Commoner (will not be present otherwise).",
                "type": ["string"]
            },
            "commoner_suspended_end": {
                "description": "Represents when the card is set to be unsuspended in Commoner. Contains a displayable text describing when it will be unsuspended if it is currently suspended (will not be present otherwise).",
                "type": ["string"]
            },
            "ll_restricted": {
                "description": "A boolean representing if the card is currently restricted in Living Legend.",
                "type": ["boolean"]
            },
            "ll_restricted_affects_full_cycle": {
                "description": "A boolean representing if the full pitch cycle is restricted - ex: only 1 card with the same name from *all* pitches can be played (will not be present if the card is not restricted).",
                "type": ["boolean"]
            },
            "ll_restricted_start": {
                "description": "The date the card became banned in Living Legend (will not be present otherwise).",
                "type": ["string"]
            },
            "referenced_cards": {
                "description": "Contains a list of unique IDs representing the various cards referenced by this card.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "cards_referenced_by": {
                "description": "Contains a list of unique IDs representing the various cards that reference this card.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "printings": {
                "description": "Contains a list of objects representing the various printings of the card.",
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "unique_id": {
                            "description": "A UUID representing the printing within this data set.",
                            "type": "string"
                        },
                        "set_printing_unique_id": {
                            "description": "A UUID representing the set printing the printing belongs to within this data set.",
                            "type": "string"
                        },
                        "id": {
                            "description": "The ID of the card printing.",
                            "type": "string"
                        },
                        "set_id": {
                            "description": "The ID of the set the card is printed in.",
                            "type": "string"
                        },
                        "edition": {
                            "description": "The edition of the set the card is printed in.",
                            "type": "string"
                        },
                        "expansion_slot": {
                            "description": "Whether the card printing comes in the expansion slot or not",
                            "type": "boolean"
                        },
                        "foiling": {
                            "description": "The foiling the card printing comes in.",
                            "type": "string"
                        },
                        "rarity": {
                            "description": "A shortcode representing the rarity the card printing was printed at.",
                            "type": "string"
                        },
                        "artist": {
                            "description": "The artist of the card printing.",
                            "type": "string"
                        },
                        "art_variation": {
                            "description": "A shortcode representing the special art treatment or variation the card was printed with, if any.",
                            "type": ["string", "null"]
                        },
                        "flavor_text": {
                            "description": "The flavor text of the card, formatted in Markdown.",
                            "type": "string"
                        },
                        "flavor_text_plain": {
                            "description": "The flavor text of the card, formatted in plain text.",
                            "type": "string"
                        },
                        "image_url": {
                            "description": "An official LSS image URL of the card printing, if it exists.",
                            "type": ["string", "null"]
                        },
                        "tcgplayer_product_id": {
                            "description": "The TCGPlayer product ID of the card printing, if it exists.",
                            "type": ["string", "null"]
                        },
                        "tcgplayer_url": {
                            "description": "A URL to TCPlayer product listing of the card printing, if it exists.",
                            "type": ["string", "null"]
                        },
                        "double_sided_card_info": {
                            "description": "All of the data for the double-sided cards this card printing is a part of.",
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "other_face_unique_id": {
                                        "description": "The Unique ID of the card printing that is the other face of this double-sided card.",
                                        "type": "string"
                                    },
                                    "is_front": {
                                        "description": "A boolean representing whether this card printing is the front or back of the double-sided card.",
                                        "type": "boolean"
                                    },
                                    "is_DFC": {
                                        "description": "A boolean representing whether this double-sided card is a Double Face Card (ex: Invoke Tomeltai / Tomeltai).",
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "other_face_unique_id",
                                    "is_front",
                                    "is_DFC"
                                ]
                            }
                        }
                    },
                    "required": [
                        "unique_id",
                        "set_printing_unique_id",
                        "id",
                        "set_id",
                        "edition",
                        "expansion_slot",
                        "foiling",
                        "rarity",
                        "artist",
                        "art_variation",
                        "flavor_text",
                        "flavor_text_plain",
                        "image_url"
                    ]
                }
            }
        },
        "required": [
            "unique_id",
            "name",
            "pitch",
            "cost",
            "power",
            "defense",
            "health",
            "intelligence",
            "types",
            "card_keywords",
            "abilities_and_effects",
            "ability_and_effect_keywords",
            "granted_keywords",
            "removed_keywords",
            "interacts_with_keywords",
            "functional_text",
            "functional_text_plain",
            "type_text",
            "played_horizontally",
            "blitz_legal",
            "cc_legal",
            "commoner_legal",
            "blitz_living_legend",
            "cc_living_legend",
            "blitz_banned",
            "cc_banned",
            "commoner_banned",
            "upf_banned",
            "blitz_suspended",
            "cc_suspended",
            "commoner_suspended",
            "ll_restricted",
            "printings"
        ]
    }
}

=== the-fab-cube/flesh-and-blood-cards/json/german/card.json
[
    {
        "unique_id": "pBpLPQ7kg6mkBpNMMPdCD",
        "name": "Herz von Fyendal",
        "pitch": "3",
        "cost": "",
        "power": "",
        "defense": "",
        "health": "",
        "intelligence": "",
        "types": [
            "Allgemein",
            "Ressource",
            "Edelstein"
        ],
        "card_keywords": [
            "Legendär"
        ],
        "abilities_and_effects": [],
        "ability_and_effect_keywords": [],
        "granted_keywords": [],
        "removed_keywords": [],
        "interacts_with_keywords": [],
        "functional_text": "**Legendär** *(Du darfst Herz von Fyendal nur einmal in deinem Deck haben.)*\n\nWenn du Herz von Fyendal pitchst und weniger {h} als ein gegnerischer Held hast, erhälst du 1{h}.",
        "functional_text_plain": "Legendär (Du darfst Herz von Fyendal nur einmal in deinem Deck haben.)\nWenn du Herz von Fyendal pitchst und weniger {h} als ein gegnerischer Held hast, erhälst du 1{h}.",
        "type_text": "Allgemein Ressource - Edelstein",
        "played_horizontally": false,
        "blitz_legal": true,
        "cc_legal": true,
        "commoner_legal": false,
        "blitz_living_legend": false,
        "cc_living_legend": false,
        "blitz_banned": false,
        "cc_banned": false,
        "commoner_banned": false,
        "upf_banned": false,
        "blitz_suspended": false,
        "cc_suspended": false,
        "commoner_suspended": false,
        "ll_restricted": false,
        "printings": [
            {
                "unique_id": "fWrG7GN6Wh9GkNBjWdkkh",
                "set_printing_unique_id": "TJn6DFWGBDfHJMntFCcmR",
                "id": "1HP000",
                "set_id": "1HP",
                "edition": "N",
                "foiling": "R",
                "rarity": "F",
                "expansion_slot": false,
                "artist": "Adolfo Navarro",
                "art_variation": null,
                "flavor_text": "",
                "flavor_text_plain": "",
                "image_url": "https://storage.googleapis.com/fabmaster/cardfaces/2022-1HP/DE/DE_1HP000_1.png"
            }
        ]
    },
    {
        "unique_id": "N77hdGp96fNQnzc79hqN9",
        "name": "Auge von Ophidia",
        "pitch": "3",
        "cost": "",
        "power": "",
        "defense": "",
        "health": "",
        "intelligence": "",
        "types": [
            "Allgemein",
            "Ressource",
            "Edelstein"
        ],
        "card_keywords": [
            "Legendär",
            "Sortiere 2 um"
        ],
        "abilities_and_effects": [],
        "ability_and_effect_keywords": [],
        "granted_keywords": [],
        "removed_keywords": [],
        "interacts_with_keywords": [],
        "functional_text": "**Legendär** *(Du darfst Auge von Ophidia nur einmal in deinem Deck haben.)*\n\nWenn du Auge von Ophidia pitchst, **sortiere 2 um**.",
        "functional_text_plain": "Legendär (Du darfst Auge von Ophidia nur einmal in deinem Deck haben.)\nWenn du Auge von Ophidia pitchst, sortiere 2 um.",
        "type_text": "Allgemein Ressource - Edelstein",
        "played_horizontally": false,
        "blitz_legal": true,
        "cc_legal": true,
        "commoner_legal": false,
        "blitz_living_legend": false,
        "cc_living_legend": false,
        "blitz_banned": false,
        "cc_banned": false,
        "commoner_banned": false,
        "upf_banned": false,
        "blitz_suspended": false,
        "cc_suspended": false,
        "commoner_suspended": false,
        "ll_restricted": false,
        "printings": [
            {
                "unique_id": "zrDP7JGF6hnMLhTrpHRhK",
                "set_printing_unique_id": "TJn6DFWGBDfHJMntFCcmR",
                "id": "1HP000",
                "set_id": "1HP",
                "edition": "N",
                "foiling": "R",
                "rarity": "F",
                "expansion_slot": false,
                "artist": "Alexandra Malygina",
                "art_variation": null,
                "flavor_text": "",
                "flavor_text_plain": "",
                "image_url": "https://storage.googleapis.com/fabmaster/cardfaces/2022-1HP/DE/DE_1HP000_2.png"
            }
        ]
    },
    {
        "unique_id": "pkMGCRh9fDT98dRgnQF8W",
        "name": "Scherbe der Erznacht",
        "pitch": "3",
        "cost": "",
        "power": "",
        "defense": "",
        "health": "",
        "intelligence": "",
        "types": [
            "Runenklinge",
            "Ressource",
            "Edelstein"
        ],
        "card_keywords": [
            "Legendär",
            "Viserai-Spezialisierung"
        ],
        "abilities_and_effects": [],
        "ability_and_effect_keywords": [],
        "granted_keywords": [],
        "removed_keywords": [],
        "interacts_with_keywords": [],
        "functional_text": "**Legendäre Viserai-Spezialisierung** *(Du darfst Scherbe der Erznacht nur einmal in deinem Deck haben und nur dann, wenn Viserai dein Held ist.)*\n\nWenn du Scherbe der Erznacht pitchst, erstelle ein Runengesang-Token.",
        "functional_text_plain": "Legendäre Viserai-Spezialisierung (Du darfst Scherbe der Erznacht nur einmal in deinem Deck haben und nur dann, wenn Viserai dein Held ist.)\nWenn du Scherbe der Erznacht pitchst, erstelle ein Runengesang-Token.",
        "type_text": "Runenklinge Ressource - Edelstein",
        "played_horizontally": false,
        "blitz_legal": true,
        "cc_legal": true,
        "commoner_legal": false,
        "blitz_living_legend": false,
        "cc_living_legend": false,
        "blitz_banned": false,
        "cc_banned": false,
        "commoner_banned": false,
        "upf_banned": false,
        "blitz_suspended": false,
        "cc_suspended": false,
        "commoner_suspended": false,
        "ll_restricted": false,
        "printings": [
            {
                "unique_id": "BLNk76c8brjQGFJGdT9Km",
                "set_printing_unique_id": "TJn6DFWGBDfHJMntFCcmR",
                "id": "1HP000",
                "set_id": "1HP",
                "edition": "N",
                "foiling": "R",
                "rarity": "F",
                "expansion_slot": false,
                "artist": "Maxim Kostin",
                "art_variation": null,
                "flavor_text": "",
                "flavor_text_plain": "",
                "image_url": "https://storage.googleapis.com/fabmaster/cardfaces/2022-1HP/DE/DE_1HP000_3.png"
            }
        ]
    }
]
