=== the-fab-cube/flesh-and-blood-cards/json-schema/set-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "unique_id": {
                "type": "string"
            },
            "id": {
                "type": "string"
            },
            "name": {
                "type": "string"
            },
            "printings": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "unique_id": {
                            "type": "string"
                        },
                        "edition": {
                            "type": "string"
                        },
                        "start_card_id": {
                            "type": "string"
                        },
                        "end_card_id": {
                            "type": "string"
                        },
                        "initial_release_date": {
                            "type": ["string", "null"]
                        },
                        "out_of_print": {
                            "type": "boolean"
                        },
                        "card_database": {
                            "type": ["string", "null"]
                        },
                        "product_page": {
                            "type": ["string", "null"]
                        },
                        "collectors_center": {
                            "type": ["string", "null"]
                        },
                        "card_gallery": {
                            "type": ["string", "null"]
                        },
                        "release_notes": {
                            "type": ["string", "null"]
                        },
                        "set_logo": {
                            "type": ["string", "null"]
                        }
                    },
                    "required": [
                        "unique_id",
                        "edition",
                        "start_card_id",
                        "end_card_id",
                        "initial_release_date",
                        "out_of_print",
                        "card_database",
                        "product_page",
                        "collectors_center",
                        "card_gallery",
                        "release_notes",
                        "set_logo"
                    ]
                }
            }
        },
        "required": [
            "id",
            "name",
            "printings"
        ]
    }
}

=== the-fab-cube/flesh-and-blood-cards/json/german/set.json
[
    {
        "unique_id": "DGq7jN9CfcpnDRQFMTHhB",
        "id": "1HP",
        "name": "History Pack 1 – Black Label",
        "printings": [
            {
                "unique_id": "TJn6DFWGBDfHJMntFCcmR",
                "edition": "N",
                "start_card_id": "1HP000",
                "end_card_id": "1HP427",
                "initial_release_date": "2022-06-01T00:00:00.000Z",
                "out_of_print": false,
                "card_database": null,
                "product_page": "https://fabtcg.com/products/booster-set/history-pack-1-black-label/",
                "collectors_center": "https://fabtcg.com/collectors-centre/history-pack-1/",
                "card_gallery": "https://fabtcg.com/resources/card-galleries/history-pack-1-black-label-de-fr-sp-it/history-pack-1-black-label-german/",
                "release_notes": null,
                "set_logo": null
            }
        ]
    },
    {
        "unique_id": "qRBNhJMCjcgWMMwGpbqMm",
        "id": "2HP",
        "name": "History Pack 2 – Black Label",
        "printings": [
            {
                "unique_id": "BmJqGfjkkFHdzHWTkfzpz",
                "edition": "N",
                "start_card_id": "2HP000",
                "end_card_id": "2HP533",
                "initial_release_date": "2023-02-24T00:00:00.000Z",
                "out_of_print": false,
                "card_database": null,
                "product_page": "https://fabtcg.com/articles/history-pack-2/",
                "collectors_center": "https://fabtcg.com/collectors-centre/history-pack-2/",
                "card_gallery": "null",
                "release_notes": null,
                "set_logo": null
            }
        ]
    }
]
